### ISSUE TITLE
Author/committer is always blank

### ISSUE THREAD

**Issue by mhenry1384** [rfennell/vNextBuild#139]
### VSTS Extension you are using
Generate Release Notes Build Task 

### Where are you running it?
*on-premise TFS 2015 
Version 14.95.25122.0

### Version of Extension/Task
2.10.2 (also saw this on 1.x)

### Expected behavior and actual behavior
author, commiter, and push are always blank

•	csdetail: @{treeId=c9cb8b1055f99c3dc4d726df473d8fe2aa3c9e12; push=; commitId=2ba62ab064567df2d390321c3bc5119b31457def; author=; committer=; comment=PR 1797: Merge feature/qaFixes to nightly
•	csdetail: @{treeId=c9cb8b1055f99c3dc4d726df473d8fe2aa3c9e12; push=; commitId=ff6c388542152516aa7d2f147b194991fc3020a1; author=; committer=; comment=Merge branch 'nightly' of ....

### Steps to reproduce the problem
use the included "Associated change sets/commits (Dump of all fields)"

**Comment by rfennell** [comment]
The issue is that the basic dump template does not recurse through the whole of the object model, it just renders strings/ints etc. The author and commiter are both complex objects not simple strings, so they appear blank. 

If you want anything from these properties you need to refer to specific fields within the object as shown below. 

Note that the double **$($.....)** format is important as we need to render the whole of the line with in the brackets as a single item

```
$($csdetail.author.date)
$($csdetail.author.email)
$($csdetail.author.name)
$($csdetail.committer.date)
$($csdetail.committer.email)
$($csdetail.committer.name)

```
