### ISSUE TITLE
GenerateReleaseNotes - The remote server returned an error: (401) Unauthorized.

### ISSUE THREAD

**Issue by joshan1120** [rfennell/vNextBuild#181]
### VSTS Extension you are using
GenerateReleaseNotes

### Where are you running it?
on-premise TFS Version 15.117.26714.0

### Version of Extension/Task
newest version, just downloaded today

### Expected behavior and actual behavior
Expected behavior is for auth to pass. I am getting the following error when using "Use Default Creds" and when not using it.

System.Management.Automation.MethodInvocationException: Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (401) Unauthorized." ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized.

My agents are running as "Network Service" could this be the issue?

**Comment by joshan1120** [comment]
We would like to use the OAuth token which is available as part of the build process.

**Comment by ChrisLGardner** [comment]
You should be able to just tick the box that allows scripts to use the OAuth token of the agent. If you then set the step to not use Default Creds then you should be fine.

If you still have problems then I'll dig into it further.

**Comment by joshan1120** [comment]
I have tried that.

System.Management.Automation.MethodInvocationException: Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (401) Unauthorized." ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized.

The other tasks are passing it like this.

![image](https://user-images.githubusercontent.com/22891676/31726468-b0d4b5a4-b3ec-11e7-938c-9abb8ef5bae8.png)

**Comment by ChrisLGardner** [comment]
I'll have to investigate this more then, I was under the impression that you only needed to enable the use of OAuth for this task to work correctly as it pulls that out of the environment variables.

something worth looking at would be the permissions given to the Project Collection Build Service user, that's what is used for the API calls so could be a permission somewhere denying read on various things. 

I've got another possible area that could be causing the problem, it might be a few days before I can get into this properly though.

**Comment by joshan1120** [comment]
Thanks Chris, I will keep digging also.

**Comment by rfennell** [comment]
I have been out the loop for a while, so sorry for the delay in getting involved. Not sure if you are still having problems.

As I wrote the task I might be able to provide some insight, so a few points I would comment on

- The is no support for oAuth in this task, it does not need it as the task is already running in the context of the build/release agent
- Checking the 'allow this build to access oAuth' as @ChrisLGardner  says is only needed to make environment variable etc. available to other process e.g. if you want one build to trigger another build.
- This task should just work auth wise the build /release agent always has the rights to access the REST API on the server that the build/release was triggered on. To be honest there should be no need to even select the 'Use default creds'. This was only put in for one client strange on prem edge case.
- It is interesting your comment that you are running as 'network service', something I would never recommend for any service (TFS or otherwise) as it make cross machine security awkward in a domain and anyway you always want to run services as lowest privileged. For this reason my TFS test box (and all production systems I run) have a **mydomain\tfsservice** account for the server process and **mydomain\tfsbuild** for the build agents.

So are you still having any problems?

Have you also looked at my CrossPlatform Generate Release Notes (also in the market place), it is written in Node.JS and I wonder if it has similar issues.

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
