### ISSUE TITLE
XmlFileUpdateTask error: Use of const in strict mode

### ISSUE THREAD

**Issue by mikevanoo-fsg** [rfennell/vNextBuild#212]
### VSTS Extension you are using
File Utilities Build Tasks - XmlFileUpdateTask

### Where are you running it?
On-Premise TFS2015
NodeJS on the build agent has been updated to 8.9.1 - this made no difference.

### Version of Extension/Task
3.0.26

### Expected behavior and actual behavior
Expected:
Attribute value in xml file is updated with the required value.

Actual:
The following error is reported:

```
Set workingFolder to default: D:\TFSBuild\agent\tasks\XmlFileUpdateTask\3.0.26
D:\TFSBuild\agent\tasks\XmlFileUpdateTask\3.0.26\FileUpdate.js:3
const FileUpdateFunctions_1 = require("./FileUpdateFunctions");
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

### Steps to reproduce the problem
Install the extension
Add XmlFileUpdateTask step to a build and configure
Run the build

**Comment by rfennell** [comment]
As a quick work around if can always use the V2 version of the extension, assuming you had it installed. This uses the older PowerShell based version.

I will test it on my local dev TFS instance, can't see an obvious reason why it wants a Let as opposed to Const - Needs some investigation

**Comment by mikevanoo-fsg** [comment]
Thanks for the quick reply. v3.0.6 was the first version I installed. Are older versions hosted somewhere?

**Comment by rfennell** [comment]
Unfortunately as you are not using VSTS you cannot just pick an older major release of an installed extension from the drop down on the task properties page. I don't think the marketplace allows the downloading of an older version for on premises.

However I have older builds archived within the VSTS CI/CD pipeline for the extensions so here is a link to a ZIP of the VSIX for the previous major version.
[richardfennellBM.BM-VSTS-FileCopier-Tasks-2.3.2.zip](https://github.com/rfennell/vNextBuild/files/1491600/richardfennellBM.BM-VSTS-FileCopier-Tasks-2.3.2.zip). You will need to removed the newer version as any upgrade needs to have a higher version number that any already installed.

Difference between 2.x and 3.x is that this older version of the XML Updater was written in PowerShell so a completely different code base. So should avoid any Node issues. Not a great solution, but a quick fix.

I don't have a TFS 2015 server to hand, all of my test instances are TFS 2017 or 2018. 

As a sideline, is there a reason you are still on 2015? I would really recommend trying to keep up to date with the major updates of on prem TFS. You are missing out on loads of great features. But let me guess corporate shared SQL version issues preventing an upgrade?

But back to the main point, I am retesting 3.x on TFS 2017 and will report back

**Comment by rfennell** [comment]
I have found some time today and retested the task on TFS 2017 using the shipping 1.105 build agent and the task works fine.

I think the issue is that TFS 2015 has just too older version of build agent (1.86?), and as I understand it is the build agent that 'carries' and internal version of Node. Hence the issues.

You could try running the TFS 2017 or later build agent, but I am not sure this is supported for TFS 2015. As I remember in that version of TFS the build agent was matched to the TFS server update version.

I need to build a TFS 2015 to prove all of this, and unfortunately I don't have time at present. Also my preferred solution would be to correct the manifest of the task to require the version shipped with TFS 2017. I see no value in updating the task for what is in effect a legacy version of TFS, especially as TFS 2018 has now shipped 

Sorry I don't have a better answer, but let me know if the 2.x version workaround works for you.

**Comment by mikevanoo-fsg** [comment]
Thanks for your quick efforts. Yes, we should have moved to TFS 2017 this year but deadlines (lots of) got in the way. January (fingers crossed). We also have quite a few XAML builds so can't moved to 2018 just yet. 

I'll give the older version a go and let you know.

**Comment by mikevanoo-fsg** [comment]
The older version works fine. Thanks again for your help.

**Comment by rfennell** [comment]
Glad we got you unblocked
