### ISSUE TITLE
Unable to specify an acceptable number of violations in StyleCopy Test Runner.

### ISSUE THREAD

**Issue by Steveip** [rfennell/vNextBuild#23]
In Team CIty The Stylecop build step allows for a maximum number of violations that can occur before the analysis is failed. This feature appears to be either not working or missing. 

Checking "Test Errors as Warnings" treats all violations as just warning irrespective of the Max. Violation Count. Where as leaving it unchecked, any violations will cause and error  even when the Max. Violation Count is set higher that the number of violations.

**Comment by rfennell** [comment]
This VSTS build extension is a basic wrapper for the [StyleCopCmdLine ](https://github.com/rfennell/StyleCopCmdLine) so I suspect any issue will be here.

I have checked the code the StyleCopCmdLine repo and behaves as I would expect, the same way the old TFS XAML based build task worked (because that is what it is based upon)
 
I have just commited a couple of extra unit tests to show the behaviour 'Check_a_maxviolationscount_used_when_violations_are_errors' and 'Check_a_maxviolationscount_used_when_violations_are_warnings'.

In both case when we get to the maximum number of violations, irrespective of whether they are treated as warnings or errors the analysis stops. 

So the Max. Violation Count is only used as an limit to stop when the violations exceed the limit. If this is not the behaviour you want could you express what is required as a unit test. Or provide a pull required with the code you wish included

I am not ruling out an issue with the wiring of the VSTS task to the underlying logic, but can see noth

**Comment by Steveip** [comment]
Ok my error, I accept that the code is working as designed. My post was more of a feature request.

Thanks

**Comment by rfennell** [comment]
No problem, still happy for anyone to help add features if they have time.
