### ISSUE TITLE
Versioning: VersionDotNetCoreAssemblies broken

### ISSUE THREAD

**Issue by EricSch** [rfennell/vNextBuild#296]
### VSTS Extension you are using
Versioning

### Where are you running it?
on-premise TFS 2018

### Version of Extension/Task
1.36

### Expected behaviour and actual behaviour
Correct version fields in the .csproj file will be updated.
Right now `<TargetFrameworks>` or `<TypeScriptToolsVersion>` are updated but not `<VersionPrefix> `and `<VersionSuffix>`? 
Only Version fields in a .NET Core Projects are `<VersionPrefix>, <VersionSuffix> and <Version>`. I think only those should be updated.

**Comment by rfennell** [comment]
Yes 1.36 does seem to have introduced an issued an issue.

The immediate workaround is to use the task a number of times, each with a specific field name.

I am looking at a proper fix now

**Comment by EricSch** [comment]
I have to precicse my issue. I mixed the issue #295 with this one. 
It's by design that `<TargetFrameworkVersion>` (not `<TargetFrameworks>`) and `<TypeScriptToolsVersion>` will be updated in a .NET project.
Still the issue with `<Version*>`. Perhaps using as default multiple fields, like `<VersionPrefix>, <VersionSuffix> and <Version>`?

**Comment by willyt150** [comment]
Thank you for the quick fix on this! I just confirmed that this fixed the issue for us.

We had done the workaround of explicitly specifying the version field, but it's nice to have it back to the default.

@rfennell just to make sure I understand, in the default "wildcard" state I need to ensure that the <Version></Version> element exists in the .csproj file, because it won't auto-add it if missing, correct?

**Comment by rfennell** [comment]
@willyt150 yes you are correct the 'wildcard mode' only updates existing fields it does not add any

**Comment by EricSch** [comment]
Happens again, all my builds are broken again
