### ISSUE TITLE
Passing a Scriptblock mades the module cumbersome to manage

### ISSUE THREAD

**Issue by boojew** [rfennell/vNextBuild#313]
### VSTS Extension you are using
Pester Test Running on VSTS

### Where are you running it?
VSTS

### Version of Extension/Task
7.x

The problem we have is that we create multiple pester tests per repo - and for some, we would like to pass the test a secure variable from VSTS. To do this, we would like to use the scriptblock functionality in the extension; however, if we do this - we ostensibly pass all pester tests in the repo the parameter forcing the ones not expecting it to fail. To compensate, I've build inline scripts that grab these secrets and force them into env variables, but it is very messy to do at scale. I see a few ways that maybe this could be handled:

1. Instead of passing the variable directly to the test, pass it to the build agent as an env variable. Then the individual tests would just need to fetch it. This would emulate the normal way variables are handled.
2. Implement an include/exclude filter so that we can continue to use a wildcard to capture all tests and exclude specific ones for which we would want to pass params on.

Thanks!

**Comment by ChrisLGardner** [comment]
If you use the Pester method of supplying script names and their parameters in the Path box then it will support individual scripts having different parameters:

`@{Path='.\tests\script.tests.ps1'; Parameters=@{fancypants="$(SecretValue)"; port=$port}; Path='.\tests\script2.tests.ps1'; Parameters=@{otherparam="$(DifferentValue)"}}`

However this can be pretty unwieldy to manage and maintain, often requiring copy/pasting into a text editor to update.

Your suggested approach 1 is already in place because of the way VSTS handles build variables. If you set default values on your parameters in your scripts to make use of them then you'll be able to use them in the build process without passing anything in and still be able to use them outside the build process. An example of this is:

```
param (
    [string]$Var1 = $Env:Var1,

    [string]$SecrectVar = $Env:SecretVar
)
```

Each of the build variables becomes an $Env variable, any '.' in them are replaced with '_' (and they are upper cased but that's not really important).

Give that a try and let me know how it works out for you.

**Comment by boojew** [comment]
The problem is specifically with secret variables which are not handled the same way as normal ones. i.e. they do not get stored in env variables but must be passed as part of the build task. https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables?view=vsts&tabs=batch

**Comment by ChrisLGardner** [comment]
I guess it depends on how many of those you have. If it's not a lot then you might need to resort to using the hashtable method above for the secrets and let default values handle the others. If it's a lot then I don't think there is a nice way we can handle that dynamically, in a scalable way.

**Comment by ChrisLGardner** [comment]
Closing this as it's been open for a while with no further comments.
