### ISSUE TITLE
conditional items resolving

### ISSUE THREAD

**Issue by BlackMoon** [rfennell/vNextBuild#35]
Hi !

Is it possible to include in template conditions (_powershell if ()_)?

I need to filter associated workitems in build release notes.

Thanks.

**Comment by rfennell** [comment]
Everything is possible, happy to look at pull requests. How do you see it working? Filter on IDs, Text?

**Comment by BlackMoon** [comment]
My purpose is to filter by ['System.WorkItemType'] field

`###Version
@@WILOOP@@
$(if ($widetail.fields.'System.WorkItemType' -eq "Version") { return "* $($widetail.fields.'System.Title') $($widetail.fields.'System.Description')" })
@@WILOOP@@

###Other associated items  
@@WILOOP@@
$(if ($widetail.fields.'System.WorkItemType' -ne "Version") { return "* **$($widetail.fields.'Ntc.ExtTask.ExternalId')** $($widetail.fields.'System.Title') $($widetail.fields.'System.Description')" })
@@WILOOP@@
`

**Comment by rfennell** [comment]
I have been having a think about this. The problem is that in the current task each line in the template is rendered one at a time. This means in the example line

`$(if ($widetail.fields.'System.WorkItemType' -eq "Version") { return "* $($widetail.fields.'System.Title')" } 
`
should already work, rendering the title for version work item types.

However I suspect this is of limited use, you really want the 'if' to wrapper a few lines of the template. To got this functionality there are few choices I can see

* Render multiple lines together - a major re-architect, don't fancy that
* Add some new @@IF@@ keywords e.g.

```
@@WILOOP@@
@@IF@@  Condition $(if ($widetail.fields.'System.WorkItemType' -eq "Version")
 ' lines to render
@@ENDIF@@
@@WILOOP@@

```
* Just add a condition extension to the exisitng keywords e.g.

```
@@WILOOP@@ Condition $(if ($widetail.fields.'System.WorkItemType' -eq "Version")
 ' lines to render
@@WILOOP@@

```
I think I favour the last option

**Comment by BlackMoon** [comment]
Ok, thanks.
Looking forward new version.

**Comment by rfennell** [comment]
I had a go at the logic for this feature, you can find it in this [Gist](https://gist.github.com/rfennell/02d0e0981d99a5ee34d8e07fe72b4dc4) 

The idea is that I allow a filter to be placed on any of the @@LOOP@@ tags, if present this is evaluated to decided if a given block is rendered for a specific build/workitem/changeset.

This  [Gist](https://gist.github.com/rfennell/02d0e0981d99a5ee34d8e07fe72b4dc4) shows the evaulation logic, but not how it would be applied to the stack based block handling logic.

The reason I stopped here is due to a comment made by @ChrisLGardner  over security. At present the    Release Management tasks uses a **Render** function to expand any variables available e.g. a build details. This **Render** does not execute any code, to do that I need to use **Invoke-Expression**. The problem is do we want to provide a mechanism so any random bit of PowerShell could be invoked via a template? I am not sure, is this worse than adding a PowerShell task to the build? It does potentially mean someone without build edit rights could put logic into a build.

I have no immediate plans to add to add this functionality, but if you want to fork and try it out then the  [Gist](https://gist.github.com/rfennell/02d0e0981d99a5ee34d8e07fe72b4dc4)  should provide a starting point

**Comment by insanity13** [comment]
> Render function to expand any variables available e.g. a build details. This Render does not execute any code, to do that I need to use Invoke-Expression

Don't understand the explanation. Render uses ""@`"`n$str`n`"@" | iex" which is 'Invoke-Expression'.

**Comment by insanity13** [comment]
Sorry, got it!
