### ISSUE TITLE
Can't use xplat release notes after installing?

### ISSUE THREAD

**Issue by deregtd** [rfennell/vNextBuild#368]
Hello!  I'm a Microsoft employee and have installed the crossplatform release notes tool into our vsts instance, but I'm unable to find the task itself to add to my build steps now that I've installed the xplat extension.  There's still the original "Generate Release Notes" task that isn't xplat and errors on osx build machines, but nothing that I can find to run on OSX build machines. :(

**Comment by rfennell** [comment]
The cross platform task is only supported in releases, this is because it uses the same API calls as the VSTS UI generate the list of associated WI/CS between release.

These API are not available for builds, hence the task will not appear in a build definition.

I wrote the old PowerShell based version of the generate release notes that support builds and releases a long time ago, and it uses my own logic to generate the WI/CS list. When I chose to write to Xplat version I decided it was better to move to the same API as used by VSTS so as to be consistent with VSTS.

Given the volume of code in the task I have no plans to port the PowerShell version over to Node.

However, it might be possible to run the tasks as PowerShell core, I need to look into that, can't promise when I will have time though

**Comment by deregtd** [comment]
Aha!  Interesting.  Okay, thanks for the note!  I know that some guys on another team nearby wrote up some custom stuff to do it all in VSTS for a build, so I may have to see what they have kicking around, was just hoping to use stuff from the community for the incremental automated CI builds for the internal dev crowd (rather than full-on releases.) I'll have to poke into the releases system to see if I can hack this into my workflow though. :)

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
