### ISSUE TITLE
Generate Release Notes Build Task not getting work items and commits from different project

### ISSUE THREAD

**Issue by AhmedGhamry** [rfennell/vNextBuild#379]
### VSTS Extension you are using
*Generate Release Notes Build Task*

### Where are you running it?
*VSTS*

### Version of Extension/Task
*2.**

### Expected behaviour and actual behaviour
Expected to get work items, change sets and commits from build artifacts located in diff vsts project,
actual behaviour, Getting None as response
###Associated work items  
None
###Associated change sets/commits  
None
### Steps to reproduce the problem

- Create build in vsts project
- Run Build with story/task attached
- Create release pipeline in another vsts project
- Add previously created build artifacts and add  Generate Release Notes task then run the release
- I use inline powershell task to print out releasenotes.md

**Comment by rfennell** [comment]
As you mention 'build' I am assuming that you are using the PowerShell version of this task (that works in builds and releases) as opposed to the Node version (that works in releases only). They do use different APIs

Your problem is a use case I have not tested, and as all the API calls are scoped to a Team Project then I am not surprised by the result. I would need to do some testing to confirm this limitation in the API.  

If it is  a limitation then I doubt I would be fixing it, as I am focusing attention on the Node version of this extension that is cross platform and uses the same APIs as the Azure DevOps UX so you get consistent behavior, not relying on my home grown logic.

Have you tried using the other extension in a Release?

**Comment by AhmedGhamry** [comment]
Hi,
Thanks for your reply,
With the node version do you mean this [one ](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes) ?
Will give it a go and post the results here,
Thanks

**Comment by rfennell** [comment]
Yes that one

**Comment by AhmedGhamry** [comment]
Working fine with the cross platform version
even with diff folder locations artifacts,
Thanks for your attention
