### ISSUE TITLE
C# 6: property initializer is recognized as syntax error

### ISSUE THREAD

**Issue by zacko83** [rfennell/vNextBuild#6]
We installed the 'StyleCop Runner Build Task' on our VSTS to automatically block style violations from beeing merged into our master branch. Locally I didn't receive any errors, but the SC build task reported an error for the following line:

```cs
internal IList<IWorker> Workers { get; set; } = new List<IWorker>();
```

The error message reported by the build task: "SA0102 : CSharp.CsParser : A syntax error has been discovered in file..."

We use a lot of other C# 6 features as well, but the error only shows up for property initializers.

The version of the Visual StyleCop extension installed in my VS is '4.7.59.0'. The build task on the other hand is based on version '4.7.49.0'. I think it's a bug that's already been fixed in the latest version. So maybe updating the build task with the latest version could solve this problem.

**Comment by rfennell** [comment]
The current shipping 'stable' version of StyleCop is 4.7.52.0, which was shipped last week. I assume this is there version you have installed (not 4.7.59.0).

I will get the task updated to use this version. As the task is actually a wrapper for the StyleCop command line tools I have to go through a steps to get there, but will try to get it all done and tested today.

**Comment by rfennell** [comment]
I have just published a new version of the StyleCop extension (and pushed to this GitHub repo), It know wrapper 4.7.52.0. Let me know if this sorts the issues

**Comment by zacko83** [comment]
I've done a little research. The version of the visual studio extension is definitely [4.7.59.0](https://www.nuget.org/packages/Visual-StyleCop.MSBuild). But you're also right the last StyleCop version on the [codeplex](https://stylecop.codeplex.com/) site is 4.7.52.0. Obviously the VS extension is from [Visual StyleCop](https://github.com/Visual-Stylecop/Visual-StyleCop) which is a github project based on the original project on codeplex. So that's the reason for the version mess:-)

So now I'm completely confused. Now we have two separate StyleCop projects. Or will the github project replace the codeplex project?

However, it seems they fixed some of the SA0102 errors already in version 4.7.51.0, so I'm confident that the update will solve my problem:-)

Thanks a lot for your help and of course for this project in general. Great work.

**Comment by rfennell** [comment]
Looks like I might need to move this extension over to the the github version then, especially if it does not fix your issue.

Though I think I need to remembers as the Visual StyleCop site says there is a recommended move to the Rosylen based analysers, which are probably best used via SonarQube, so I am not sure how important this build task is going forward

**Comment by zacko83** [comment]
I just tested the build with the new version. Now I've got a good and a bad news:

Good news: The syntax error didn't show up again. So the new version fixed that problem.

Bad news: A new error showed up, that doesn't occur when I run StyleCop locally:
"SA1305, Message: The variable name 'isAppenderInitalized' begins with a prefix that looks like Hungarian notation. Remove the prefix or add it to the list of allowed prefixes."

Here's the line of code producing this error:
```cs
private bool isAppenderInitalized;
```

The prefix 'is' is already part of the allowed prefixes (by default). So I have no clue, why he's complaining. And again, locally I don't receive any errors. The error only shows up via the SC build task. 

It would be great, if you switch to Visual StyleCop. I'd really appreciate it.

**Comment by rfennell** [comment]
I think you are right, it is going to have to be done -  bit busy today but will get on it ASAP

**Comment by zacko83** [comment]
Sounds great. Thanks a lot for your help.

**Comment by rfennell** [comment]
Just pushed up the build that contains 4.7.59.0 StyleCop, let me know how that goes

**Comment by zacko83** [comment]
Thanks for the quick update. Unfortunately I still receive the error SA1305 for the field `isAppenderInitalized`. The SC build task is definitely up to date, I even checked on the build server, the DLLs have the latest version.

I've created a minimized sample:
[DummyProject.zip](https://github.com/rfennell/vNextBuild/files/236549/DummyProject.zip)

It only contains a class with this field and our StyleCop settings file. Locally no errors occur, but via the build task SA1305 shows up. 

Can you reproduce this behaviour?

**Comment by rfennell** [comment]
After all that it is not a bug, but planned behaviour! 

We could have worked a with the original version if II had thought a bit more....

As this task does not assume StyleCop is installed on the build machine (it deploys the DLLs as part of the task) we can't assume there is a default **stylecop.settings** file available. So by design the task makes the assumption that the **stylecop.settings** file is in the same folder as the **.csproj** file, these are the only rules used for that project. This means you can have different sets of rules for different projects e.g. one set of rules for production code and another for unit tests. 

This is of course unless you override this using one of the advanced task parameters. In which case the specified rule set is used for all projects. 

Anyway, this is unlike using StyleCop locally (in Visual Studio); here the default behaviour is to keep going up the folder structure until it finds a **styelcop.settings** file, merging them as it goes, to build a combined ruleset. This includes the adding in the default **stylecop.setting** file in the **c:\program files (x86)\StyleCop** folder.

The reason for the problem you have seen is that it seems the default list of Hungarian notation prefixes are pulled from somewhere in the **c:\program files (x86)\StyleCop** folder.

Even if you create a local **stylecop.settings** file to switch on or off some specific rules, the Hungarian notation prefixes are not set in it unless you add your own.

So the fix is going to have to be to add your own, you are going to need a **stylecop.settings** file in each for each **.csproj** folder that as well as enabling/disabling the rules you want also lists the Hungarian notation prefixes. So something like the following

```
<StyleCopSettings Version="105">
  <Analyzers>
    <Analyzer AnalyzerId="StyleCop.CSharp.NamingRules">
      <AnalyzerSettings>
        <CollectionProperty Name="Hungarian">
          <Value>is</Value>
        </CollectionProperty>
      </AnalyzerSettings>
    </Analyzer>
  </Analyzers>
</StyleCopSettings>
```

Hope that gets us to a reasonable solution, thought I don't think it was needed at least we also got onto the C#6 supported version.

**Comment by zacko83** [comment]
OMG, what you're saying sounds so logic and obvious:-)

You're absolutely right. I specified our custom settings file in the advanced task parameters, but it was configured with "Merge with settings files found in parant folders", just like you said. So we just have to switch on "Don't merge with any other settings file" and configure all 'standard settings' ourself.

Thanks so much for your help.

**Comment by vkelman** [comment]
I have SyleCop 6.1.0 running Visual Studio Enterprise 2017.
And StyleCop still marks a as syntax error SA102   legal C# 6  null-conditional  "?."  operator!

**Comment by rfennell** [comment]
Just to note that I have depricated this extension and it is not under active support. 

The details of this decision are in the [WIKI](https://github.com/rfennell/AzurePipelines/wiki/StyleCop-Runner-Task)
