### ISSUE TITLE
GenerateReleaseNotes - Skip artifact

### ISSUE THREAD

**Issue by gigeld** [rfennell/vNextBuild#60]
Our release has links two more than one build type artifacts. Is it possible to create Release notes for only one of them and skip the other ones? Thanks!

**Comment by rfennell** [comment]
I have had a think about this. there are a few options

1. Could add a flag so that the release notes are only generated for primary artifact, this feels limiting
2. Need to provide a way to enter the name of the build to generate notes for, this feels awkward and prone to error. I don't think there is a way to populate a drop down with the names of the artifacts in the release

Either is doable but neither really appeals as a solution

Can you think of a better way?

**Comment by gigeld** [comment]
I believe that option 1 [flag for primary only] would satisfy most of users.

**Comment by rfennell** [comment]
I have done the first option then, it is now public in 1.6.1

**Comment by gigeld** [comment]
Thank you for the prompt support! It works as expected.

I have another question: is there a way to extract the hyperlink address of the associated work items? Thanks!

**Comment by rfennell** [comment]
It should be available on the work item object, the tag to get the ID is

`$($widetail.id)`

The url is in same form, so it is

`$($widetail.url)`

The [MSDN REST documenation](https://www.visualstudio.com/en-us/docs/integrate/api/wit/work-items#get-a-work-item) list all the data returned
