### ISSUE TITLE
How I can get the list of the backlogs marked Done before the build in a template ?

### ISSUE THREAD

**Issue by GillesBrice** [rfennell/vNextBuild#61]

**Comment by rfennell** [comment]
I am little unclear as to what you are asking, so can't say if it is possible

1. Are you using the extension in a build or a release?
2. Could you provide a quick mock up of what you want to see generated

Behind the scenes I gather all the information before outputting anything, the only real constrain is the location of the @@LOOP@@ tags.

**Comment by GillesBrice** [comment]
1. I'm using the extension in a build.
2. I want to get the history of the work items marked Done order by date not only the work items associated to the build.

For example :
`Release notes for build SampleSolution.Master

Build Number: 20160229.3 Build started: 29/02/16 15:47:58 Source Branch: refs/heads/master

Work items

Task 60 [Assigned by: Bill ] Design`, Done in Build Number: 20160101.1
Task 61 [Assigned by: Bill ] Developpement`, Done in Build Number: 20160203.2
Task 62 [Assigned by: Bill ] Test 1`, Done in Build Number: 20160215.3
Task 63 [Assigned by: Bill ] Test 2`, Done in Build Number: 20160229.3

**Comment by rfennell** [comment]
OK I understand now, sorry in it current form I it cannot do that. The only link to work items I have is via the build associations. 

I would need to add the ability to provide a work item query as a parameter to the task to supplement the list of work items. This is not something I was planning to do.

But I do accept pull requests if someone looks at it

**Comment by rfennell** [comment]
Does the new release 2.04 help in your case?
It allows the you to get all the changes since the last successful release to a given stage.
Details in this post http://blogs.blackmarble.co.uk/blogs/rfennell/post/2017/01/05/Version-20x-of-my-Generate-Release-Notes-VSTS-Task-has-been-released-with-release-rollup-support

**Comment by GillesBrice** [comment]
In our case, we didn’t have a Release version but we will put it in place so the new release will help in our case.
Thank you.

**Comment by rfennell** [comment]
I am closing this issue as I think it is addressed with the enhancements listed in 

- GenerateReleaseNotes - Powershell (2.x and later using my custom logic to get the list of associated work items since previous release)
- GenerateReleaseNotes - Cross Platform (all versions, using Microsoft provided API to get the work items associated since previous release)

If this is not the case, reopen with issue with more details as to what we could change, note that I have no option to alter the logic of the Cross Platform version as it is designed (by using the same API) to working in an identical manner to the VSTS Release UI
