### ISSUE TITLE
Use Build Variable for TemplateFile parameter

### ISSUE THREAD

**Issue by dmunney** [rfennell/vNextBuild#66]
TFS 2017 (on-prem)

### VSTS Extension you are using
GenerateReleaseNotes

### Expected behavior and actual behavior
Expect the variable to be evaluated and substituted accordingly.  Instead, error is thrown:
Cannot find path 'c:\agent\\_work\r1\a\\$(MyPath)' because it does not exist.

### Steps to reproduce the problem
Define in variables section of Release Definition
MyPath=c:\path\to\file.txt

TemplateLocation=File
TemplateFile=$(MyPath)

**Comment by rfennell** [comment]
The reason you are seeing this result is due to the TemplateFile parameter being set as a FilePath type so you can pick the file form the source location or artifact. This has the effect that it will always prepend the entered path with that of the source/artifacts working directory as you have seen. A side effect is that this type of control does not evaluate $(XXX) variables. You need to ask Microsoft to change this behaviour, it is beyond my control. 

So what you are seeing is the expected behaviour for A FilePath parameter

The workaround is to place you template file under source control. Which obviously has the added advantage that it is versioned.
