### ISSUE TITLE
Invalid JSON Format and authorization

### ISSUE THREAD

**Issue by insanity13** [rfennell/vNextBuild#80]
### VSTS Extension you are using
Update Build Variable Task

### Where are you running it?
TFS 2017 on-premise

### Version of Extension/Task
1.1.1 (latest)

### Steps to reproduce the problem
At first "Auto-increment the variable" got Error 
`2017-02-24T12:41:07.4316583Z ##[error]System.InvalidOperationException: Преобразованная строка JSON имеет неверный формат.`

So I added "-Compress" switch to ConvertTo-Json statement
`$jsondata = $data | ConvertTo-Json -Compress -Depth 10 #else we don't get lower level items`

Then got  "(403) Forbidden"
- Edit build definitions right sets crrectly
- "Allow scripts to access OAuth token" marked on my environments

Helps me "UseDefaultCredentials" on webclient instead of Bearer token:
`    #$webclient.Headers.Add("Authorization" ,"Bearer $personalAccessToken")
	$webclient.UseDefaultCredentials = $true`

**Comment by rfennell** [comment]
Can I just check has the content of your two pull requested fixed the issues for you system?

I am not surprised you needed to use useDefaultCreditials = $true, this seems to be a common change required for on-prem usage

**Comment by rfennell** [comment]
I am write in assuming this issue related to the review by kislitsyn_mg on the marketplace?

**Comment by insanity13** [comment]
> Can I just check has the content of your two pull requested fixed the issues for you system?
But they are already created:
https://github.com/rfennell/vNextBuild/pull/82
https://github.com/rfennell/vNextBuild/pull/81

> I am write in assuming this issue related to the review by kislitsyn_mg on the marketplace?
Yes

**Comment by rfennell** [comment]
I have pulled the defaultcredenitials fix into the publically released extension, it is now an option that defaults to off, you will been to modify your build to set the flag (advanced properties) to true to make use of the defaultcredentials.

It is releases as 1.2.x

I have not put in the -compress, as after reading the MSDN documentation I cannot see why it would effect the issue. I think due to invalid credentials that you did not have any real JSON to parse

**Comment by insanity13** [comment]
About this PS bug: https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/11088063-powershell-convertto-json-error-when-has-string-wi

In PS 5.1 
![image](https://cloud.githubusercontent.com/assets/1174911/23329359/2daa001c-fb50-11e6-93b4-5d5bfaccb0c8.png)

In 4.0
![image](https://cloud.githubusercontent.com/assets/1174911/23329362/3d53e4ba-fb50-11e6-848c-8189f57fc590.png)

**Comment by insanity13** [comment]
>It is releases as 1.2.x

Thanks a lot!

**Comment by rfennell** [comment]
Glad it is fixed for you in 1.2.1. 

In the past all JSON format errors I have seen with these VSTS extension is have been due to a lack of JSON data (usually an HTML error message as opposed to JSON).  Hence my reluctance to adding extra ConvertTo-JSON parameters.

I will keep this option noted for now
