### ISSUE TITLE
CI builds Interfering with release build release notes

### ISSUE THREAD

**Issue by mcoburnwa** [rfennell/vNextBuild#84]
This issue may be more of a TFS question but I thought I'd ask in case there is a way to overcome this with this tool.  I installed the GenerateReleaseNotes build task (version 2.5.1) in our on-premises TFS system (TFS 2015 Update 3).  The extension is working quite well but I was wondering if there is a way to handle the following scenario:

We define two TFS build definitions, one for continuous integration builds (which don't use the GenerateReleaseNotes task) and a release build definition which does use the GenerateReleaseNotes task and ultimately creates a release candidate build with installers that the QA team can use to test.  In that scenario I am finding that when committing code to my repo, the CI build is triggered which is great, but later when I try to manually queue the release build the release notes won't show any associated changes because the CI build had already swallowed them up essentially.

**Comment by insanity13** [comment]
This is not the extension problem, this is how TFS associate WI/Commits with builds.
Use different build definitions for CI and manual builds (or different branches, but this is a not a good idea).

**Comment by insanity13** [comment]
Sorry, my first comment was wrong. 
Extension uses TFS API to get associated WI with build. It should work with using different build for CI and Release bulds.
We have a similar situation with builds, but it works fine. Your release build shows WI?

![image](https://cloud.githubusercontent.com/assets/1174911/23329492/545752de-fb53-11e6-8be7-4ad841d32326.png)

**Comment by rfennell** [comment]
Yes @insanity13 is correct, the way it works it the build knows its buildid, this is used to lookup the build details via the rest API which includes the associated work items and changesets.

The associated work items and changesets as linked based on the last *successful* build of the same build definition. So assuming you only run the release build when you release the product the associations should be correct, as you want.

If you want the release notes to span a number of build then this is possible if the task is used within a release pipeline as you can tell it to look for all builds since the last successful release (as opposed to build). In your case you could maybe add a release that just copies the installers (MSIs?) to a know folder for your QA team to pickup. 

But fundamentally the release notes report should match the build summary report

**Comment by mcoburnwa** [comment]
Thanks to you both for your clarification!  It was clearly not working for me after several attempts, but once I recreated one of the build definitions from scratch (had created a clone of the other originally) and ensured that the non-CI build was creating a label (it had earlier been set to create a label on a successful build but this was failing because the label included the build definition name which had a space in it) then it started to work as expected.  Anyway, I think I am in a good state now and thanks for creating such a great tool and making it available!

**Comment by rfennell** [comment]
Glad you are working now
